---

- name: Include OS variable variables
  include_vars: "{{ ansible_os_family }}.yml"

# Include OS specific config
- include: config-Debian.yml
  when: ansible_os_family == "Debian"

- include: config-RedHat.yml
  when: ansible_os_family == "RedHat"
